/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.giovanni.kotlin.sampleservice.tests

import kotlin.test.Test
import kotlin.test.assertEquals

import br.giovanni.kotlin.sampleservice.controllers.GreetingController

class GreetingControllerTest {
    @Test
    fun testAppHasAGreeting() {
      val classUnderTest = GreetingController()
      assertEquals("Hello, user", classUnderTest.greeting("user").content)
    }
}
